### ISSUE TITLE
Javascript issue

### ISSUE THREAD

**Issue by ramaem** [DPDBaltics/PrestaShop-1.7#13]
Hello,

Getting this kind of JavaScript error that mapDiv is null when selecting carriers. Any ideas what's may be the problem ? Problem started when I updated DPDBaltics module, before worked fine. Tried diffrent versions of DPDBaltics module but still same problem.

Using PrestaShop 1.7.7.2 and PHP version 7.3.27

Website address: www.japanparts.ee

To recreate the problem add product to the cart and proceed to checkout and to select carriers.

![image](https://user-images.githubusercontent.com/85620274/121345841-0553f900-c92e-11eb-9c7d-a7b9a95583a6.png)

**Comment by Maz-Invertus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Multicurrency: Icelandic króna and Japanese yen](https://trello.com/c/gx6RKyGf/194-multicurrency-icelandic-kr%C3%B3na-and-japanese-yen)

**Comment by Maz-Invertus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Start transaction > Go To payment method with mollie > go back to store issue #424](https://trello.com/c/NufphYZO/203-start-transaction-go-to-payment-method-with-mollie-go-back-to-store-issue-424)
