### ISSUE TITLE
Failed to create shipment: remark is to long

### ISSUE THREAD

**Issue by GeorgeKarpov** [DPDBaltics/PrestaShop-1.7#28]
When customer adds a comment to the order  then "Failed to create shipment: remark is to long" error occurs by saving shipment data:
![dpd_error](https://user-images.githubusercontent.com/73421397/149801920-d5ce777c-03c6-46b9-8a12-d53f523e9df7.jpg)
Solved by commenting out following line:
![dpd_code](https://user-images.githubusercontent.com/73421397/149804030-5f6918cd-13f9-4b68-a786-4500ab271ccb.jpg)

The length of related customer message is 176 characters.

PrestaShop version: **1.7.7.4**
PHP version: **7.3.31**

**Comment by loonas** [comment]
Hi @GeorgeKarpov,

I hope that you are doing well today! Thank you for reaching out to us regarding this issue.
I have forwarded the ticket details to the developer and we will keep you updated about the progress.

If you have any further questions, just let us know!

--
Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @GeorgeKarpov,

Our developer has looked into the issue, and tried recreating the issue on his side.

He was able to enter 400+ characters in the comment without the module coming across an error: 
![image](https://user-images.githubusercontent.com/30753843/150801634-c830f537-a81d-4e50-a0dc-e875857f3814.png)

Could you specify more details about the order itself? Screenshots of all of the order details would be appreciated.
If any sensitive information is present, you can share the screenshots via email to support@invertus.eu.

We will be looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by loonas** [comment]
Thank you for your reply @GeorgeKarpov!

We have received the information via email, and I have forwarded it to the developer. We will keep you updated regarding the situation via email and via here as well.

--
Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @GeorgeKarpov,

I hope that you are doing well! I wanted to inform you about the progress of this task.
Our developer has investigated it with the provided screenshot and log file, and could not replicate the issue with the given details. We tried several times recreating the order with similar details on our end, but were unable to receive the error.
We are suspecting that custom modifications could be the root of the issue.

In order to identify it further, could you also share your BO+FTP credentials to support@invertus.eu?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by GeorgeKarpov** [comment]
Hi @loonas,

Have you tried on the live API? I am asking since this error is response from API endpoint.
I guarantee that the source code of the module has not been modified.
Nevertheless it is OK for me just to comment out one line of code since I don't really see any reason to submit customer message to API.

Regards,
Georgijs Karpovs

**Comment by loonas** [comment]
Thank you for your reply @GeorgeKarpov!

I appreciate the additional details. I have asked our developer to check the live API details again, in case he would be able to pinpoint the root of the issue, and resolve it, although, at the current state, after various attempts, we could not replicate the issue.

We will keep you updated regarding this! Thank you for your understanding.

--
Best regards,
Invertus Support team

**Comment by justelis22** [comment]
Hello there,

Our development team has checked and implemented a fix regarding this issue. Functionality was tested and set up for the main release. The remark is being trimmed and special characters are shown.
![image](https://user-images.githubusercontent.com/103486043/172829336-c8423114-6d82-476f-9747-6c6c1f982ed5.png)

--
Best regards,
Invertus Support team
