### ISSUE TITLE
Employee general permission for module not saving

### ISSUE THREAD

**Issue by Laimonas-Mituzas** [DPDBaltics/PrestaShop-1.7#32]
Trying to set general permission for module
https://prnt.sc/TSYPgunXTKbj
after page reload it shows that selection is not saved.

Can't access module settings via admin menu
https://prnt.sc/4jYBKzVVEX3Q

Also LT translation is not perfect :)

PS 1.7.6.9
DPD baltics 3.2.8

Thanks

**Comment by GeorgeKarpov** [comment]
I have faced same issue. Only users with SuperAdmin profile have access to this menu.

**Comment by Pisikoll** [comment]
I didn't find what is causing the root error but I found a workaround.
run the following SQL code and this will allow to save permissions for given role.
Proper fix still required...
`UPDATE ps_tab set class_name = 'AdminDPDBalticsModule' where class_name = 'AdminDPDBalticsModule_MRT'`

**Comment by justelis22** [comment]
Hi there,
Thank you for your patience.

We will check this, and get back to you as soon as we have some updates!

Best Regards,
Invertus Support team.

**Comment by Laimonas-Mituzas** [comment]
Nice, we are going to celebrate anniversary for this issue soon. :)

**Comment by justelis22** [comment]
Hi @Laimonas-Mituzas,

Sorry for the delay, let's try to avoid the anniversary :)

You have also mentioned the issue with LT translations, could you please provide more information on where did you see the imperfections?

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there GitHub community!

We investigated your provided case scenario. After trying to set up setting differently, we noticed that whatever the settings are - module windows are not displayed. After a deeper analysis and reading the error reports raised for Prestashop, we see that this is their core error. 
Unfortunately, in this case, without the analysis of the Prestashop core and its modification, there is no possibility to achieve the needed results.

At the moment, modifying the PrestaShop core is not on our roadmap, so this issue will be closed.

Best Regards,
Invertus Support team.

**Comment by Laimonas-Mituzas** [comment]
I see. Very strange situation, because we do not experience the same issue with other shipping modules.
Thank you for your time.

**Comment by Laimonas-Mituzas** [comment]
Thank you for your time.

**Comment by gadnis** [comment]
Hi @justelis22, 
My question would be why use PrestaShop feature if it is not work properly? 
In the code you avoid using your won tabs installer if ps version is greater than 1.7.4 (`@see TabsInitializer::initializeTabsByPsVersion()`), instead the check should be avoided until PrestaShop core is fixed.

So my suggestion would be use your own `TabsInstaller` service until PrestaShop core is fixed.
If you agree with me, I could make a pull request for that, just tell me if you would like to fix the `invertus/psmoduletabs` package or modify this module only

**Comment by justelis22** [comment]
Hi @gadnis,

Thank you for contributing once again!

We will check the fix that you have made, and if everything checks out, merge the PR.

Once we have some updates, we will inform you.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hello @gadnis,

We have checked the PR, and it will require some changes from our developer, but we will modify it and implement this feature. Thank you for contributing!

As soon as we have some updates, we will let you know.

Best Regards,
Invertus Support team.

**Comment by Pisikoll** [comment]
Hi @justelis22,

How is this PR going. Will it be implemented some time in the future?

**Comment by justelis22** [comment]
Hi there @Pisikoll,

The feature will be implemented in the future, although I am not able to give you an exact time span, as we have higher-priority tasks at the moment.
You can be sure that if any updates are available, they will be posted here.

Thank you for your patience and understanding!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there, thank you everyone for your patience!

The improvement was added to the latest 3.2.15 release.

We will be waiting for your feedback.

Best Regards,
Invertus Support team.
