### ISSUE TITLE
Additional shipping fee in the product page is not calculated to final shipping price

### ISSUE THREAD

**Issue by Laimonas-Mituzas** [DPDBaltics/PrestaShop-1.7#36]
When I add additional shipping fee in product page 
https://prnt.sc/CMwXJW-1Vigz
it is  not calculated to final shipping price in checkout
https://prnt.sc/ZmCByDopYRYB
See the last custom created carrier "Raben" it has that fee added.

PS 1.7.6.9
DPD baltics 3.29.0

**Comment by justelis22** [comment]
Hey there,

We will be glad to help you with this! Our team will check your case, and get back to you as soon as possible with an update.

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @Laimonas-Mituzas,

This will be added to the next release, and as soon as it is done, we will inform you here.

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
This was added and merged into the main repository.

If there are any questions, don't hesitate to contact me!

--
Best Regards,
Invertus Support team.
