### ISSUE TITLE
Js hides dpd form on chosen search

### ISSUE THREAD

**Issue by wwatu1337** [DPDBaltics/PrestaShop-1.7#38]
When selecting a pickup point and using the chosen selects search function for any of the selects(phone, city...) and clicking elsewhere, updatedDeliveryForm is triggered which closes the whole dpd form for pickup point selection. 

Faulty code:
`//Js to open extra content failed from theme, doing it manually.
            if (!$(params.deliveryOption).next('.carrier-extra-content').is(':visible')) {
                $('.carrier-extra-content').hide();
                $(params.deliveryOption).next('.carrier-extra-content').slideDown();
            }`

**Comment by justelis22** [comment]
Hey there,

We will be glad to help you with this! Our team will check your case, and get back to you as soon as possible with an update.

--
Best Regards,
Invertus Support team.

**Comment by wwatu1337** [comment]
Created a pull request with a fix:
https://github.com/DPDBaltics/PrestaShop-1.7/pull/57

**Comment by justelis22** [comment]
Hi there @wwatu1337,

The fix for the issue was added to the 3.2.15 release.

I would like to thank you for your patience and understanding while waiting for the fix.

Your feedback is always appreciated!

--
Best Regards,
Invertus Support team.
