### ISSUE TITLE
Shipping > DPDBaltics tab invisible for employee with custom permissions

### ISSUE THREAD

**Issue by gadnis** [DPDBaltics/PrestaShop-1.7#42]
DPDBaltics tab is not visible for team member with different profile than SuperAdmin.

How to reproduce:
1. Add all DPDBaltics permission to custom employee profile acount [screenshot](https://prnt.sc/7TeXfRYZccNM)
2. Login with custom employee account credentials to prestashop admin page.
3. You can see the missing DPDBaltics tab [screenshot](https://prnt.sc/cu6ZEFqC5vA5)

**Comment by justelis22** [comment]
Hi there @gadnis,

We investigated your provided case scenario here in this GitHub issue - https://github.com/DPDBaltics/PrestaShop-1.7/issues/32
Unfortunately, in this case, without the analysis of the Prestashop core and its modification, there is no possibility to achieve the needed results.

At the moment, modifying the PrestaShop core is not on our roadmap, so this issue will be closed.

Best Regards,
Invertus Support team.
