### ISSUE TITLE
Fix import/export feature

### ISSUE THREAD

**Issue by gadnis** [DPDBaltics/PrestaShop-1.7#43]
Hi,

please take a look at the pull requests. I fixed import, export issues. 
Without these pull requests import/export does not work properly.

- Price rules import fix #39 
- Settings import fix #40 
- Price rules export fix #41

**Comment by justelis22** [comment]
Hi there @gadnis,

Thank you for contributing! We have seen these pull requests, and we will analyze them in more detail in the upcoming weeks.

We will inform you once we have some updates.

Best Regards,
Invertus Support team.

**Comment by gadnis** [comment]
Just to let you know it should take no more than 5 minutes to check these changes. 
It is basically a typo made in the code. 
When you see it there's no need to analyze or look at it in more details - it is obvious.

**Comment by justelis22** [comment]
Hi @gadnis,

Thank you for the additional information.
Our developer will overview the PRs, I am sure that it will not take long!

We will inform you as soon as we have some updates.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hey @gadnis,

The PRs were merged quite some time ago, so closing the issue.
If you have any comments, please let me know!

Best Regards,
Invertus Support team.
