### ISSUE TITLE
label print not working from 3.2.13 onward

### ISSUE THREAD

**Issue by wwatu1337** [DPDBaltics/PrestaShop-1.7#56]
Since 3.2.13 the label printing is not working.

On some rare occasions it actually loads the pdf, but most of the time it is just endless loading, only thing that firefox reports under transfer is "NS_ERROR_NET_PARTIAL_TRANSFER", nothing in prestashop/server logs, same behavior in every browser.

Label printing worked fine in 3.2.12

**Comment by justelis22** [comment]
Hey there @wwatu1337,

Could you please send us steps to reproduce the issue?
As well as your PS and PHP versions so that we could try to recreate the same issue from our side as well.

Some screenshots or video recordings would be helpful too!

Best Regards,
Invertus Support team.

**Comment by wwatu1337** [comment]
Hey,

so I have tried replicating it now with a fresh install and I have found some info about the issue, it seems to have something to do with SSL.

I tested on Prestashop 8.0.4, PHP 8.1, nginx 1.18 on debian 11, but this issue also was happening on prestashop 1.7.8.9 and php 7.4 starting from version 3.1.13, I have not yet tested on apache, which I can do if needed.

1. Setup fresh prestashop
2. Install dpd module starting from 3.2.13, set print from browser from module settings
3. Make test order, select dpd pickup point
4. Test label printing, from order list open eg 5 new tabs from dpd label printing button - all tabs load with pdf label
5. Install SSL from lets encrypt
6. Turn on SSL from prestashop backoffice( turn on enable ssl & enable ssl on all pages)
7. Test label printing, from order list open eg 5 new tabs from dpd label printing button - some may or may not print correctly, most of the pages load indefinitely with error NS_ERROR_UNEXPECTED 
![image](https://github.com/DPDBaltics/PrestaShop-1.7/assets/58936586/1c3a3c2b-5df0-4b36-abad-2d618abced34)
 ![image](https://github.com/DPDBaltics/PrestaShop-1.7/assets/58936586/a5b8aa7f-0886-4626-a848-8c7bc9e83472)
Do a hard refresh on each loading tab(CTRL+F5) and all the labels load correctly
8. Turn on debug mode from prestashop settings, try label printing again - works as expected on every load without hard refresh, turn off, only with hard refresh
9. Downgrade DPD module to 3.2.12 - label printing works correctly

These are the things I have found so far. The production server is also behind cloudflare, but even without cloudflare the label printing is buggy at best without debug turned on and ssl enabled, on 3.2.12 the module works correctly in every environment, so it must be something within the module.

**Comment by justelis22** [comment]
Hey there @wwatu1337,

We have analyzed the issue from our side, following the steps you have provided, and the labels are being printed without any issues.
That being said, could you please share access to your shop via email - support@invertus.eu? We would need:
Back Office credentials;
FTP and SSH credentials.

Waiting for your message!

Best Regards,
Invertus Support team.

**Comment by wwatu1337** [comment]
As debian 12 rolled out with nginx 1.22.1 this no longer seems to be an issue, be it a bug with nginx or module, who knows, but label printing is working as of now.
