### ISSUE TITLE
Failed to create shipment - street is too short

### ISSUE THREAD

**Issue by aliensun262** [DPDBaltics/PrestaShop-1.7#64]
Latest version DPD Baltics module installed and Prestashop 1.7.8.9. PHP version: 7.4.33.
![Screenshot 2023-09-13 104306](https://github.com/DPDBaltics/PrestaShop-1.7/assets/61792837/a9c99ffd-189c-4fff-b8a4-5b3511c04599)

Error on create shipment label: Failed to create shipment - street is too short.
Pickup point: Automaat Võru Maksimarket
Address: JÜRI 83
Post code: 65607
City: VÕRU
Country: EE

**Comment by justelis22** [comment]
Hi there @aliensun262,
Thanks for waiting!

We will analyze the issue and get back to you as soon as possible.

If you have something else to add, do not hesitate!

Best Regards,
Invertus Support team.

**Comment by aliensun262** [comment]
Hi, it looks like the street data is incorrect or the apartment number is missing.
But this data is not needed, since the pick-up point is selected.

**Comment by justelis22** [comment]
Hi @aliensun262,

We have checked this case, and we would need to add some validation to fix this issue.
It should be added to the upcoming release.

Best Regards,
Invertus Support team.

**Comment by aliensun262** [comment]
Hi, today we also got error to create shipment: name1 is too short ID order: 1234
Our customer registered as: A R
May be also cancel checking Name of customer?

**Comment by aurjus** [comment]
Still waiting for fix - Failed to create shipment - street is too short.

**Comment by justelis22** [comment]
Hello @aliensun262 and @aurjus,
Thanks for waiting!

We have implemented a fix, it will be added to the upcoming release.
Currently, we are in the testing phase, so once that is done, it will be released.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there,
Thanks for waiting!

The new module version is ready and can be downloaded here - https://github.com/DPDBaltics/PrestaShop-1.7/tree/v3.2.16

This issue should be fixed, but if you face any issues, don't hesitate to reach out to us with feedback!

Best Regards,
Invertus Support team.

**Comment by aurjus** [comment]
Just test 3.2.16 version. Problem still exists https://i.imgur.com/FGv5DqS.png
Note. We got this error only then Automatically generate return label option is enabled.

**Comment by justelis22** [comment]
Thanks for the feedback!

We will analyze where this is coming from and get back to you.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there,

The release 3.2.17 should have the fix for the error. You can download it here - https://github.com/DPDBaltics/PrestaShop-1.7/releases/tag/v3.2.17

We will be waiting for your feedback!

Best Regards,
Invertus Support team.
