### ISSUE TITLE
More info popover does not work

### ISSUE THREAD

**Issue by modex9** [DPDBaltics/PrestaShop-1.7#68]
When pickup container is replaced with new content after ajax call in `saveSelectedStreet`:
https://github.com/DPDBaltics/PrestaShop-1.7/blob/7cb5720d40469534faea1c43a9ed5f1adb854efa/views/js/front/pudo-search.js#L139

function `reselectDataPopover` should be called to bind the `popover` function, otherwise popover does not work, when `dpd-more-information` element is clicked.

**Comment by justelis22** [comment]
Hi there @modex9,
Thanks for waiting!

The issue was fixed in the 3.2.19 beta release - https://github.com/DPDBaltics/PrestaShop-1.7/releases/tag/v3.2.19-beta

Feel free to try it out before the official release. 
We will be waiting for your feedback!

Best Regards,
Invertus Support team.
