### ISSUE TITLE
Starting from version 3.2.16, price rules are broken

### ISSUE THREAD

**Issue by aliensun262** [DPDBaltics/PrestaShop-1.7#73]
Starting from version 3.2.16, the price in the DPD module does not change when changing the country.
Price rules don't work either. When a certain amount in the cart is reached, the price does not change.
NB! Some orders went abroad at domestic prices!?!

**Comment by justelis22** [comment]
Hi @aliensun262,

We are currently working on this issue and the fix will be included in the upcoming 3.2.18 version.
I will close this issue, as we have one for the same case open already - https://github.com/DPDBaltics/PrestaShop-1.7/issues/70
Please follow the progress there.

Best Regards,
Invertus Support team.
