### ISSUE TITLE
Choosing a country dialing code is a pain

### ISSUE THREAD

**Issue by aliensun262** [DPDBaltics/PrestaShop-1.7#74]
I have several countries selected in the DPD module, why do I need to select a phone code from 200 values?
Wouldn't it be better to limit the list of dialing codes to selected countries in the module?

**Comment by justelis22** [comment]
Hi there @aliensun262,

Thank you for the report!
We will evaluate the task and discuss with the DPD team regarding the possibilities of implementing this improvement.

For now, I would like to ask you for some patience, as we have already planned the 3.2.18 release, so this will be addressed at the beginning of next year.

Best regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @aliensun262,
Thanks for waiting!

The improvement is added to the 3.2.19 beta release - https://github.com/DPDBaltics/PrestaShop-1.7/releases/tag/v3.2.19-beta
Now only active countries in the PrestaShop configuration will be visible.

Feel free to try it out before the official release.
We will be waiting for your feedback!

Best Regards,
Invertus Support team.
