### ISSUE TITLE
DPD product (carrier) zone is Lithuania but visible to other country addresses

### ISSUE THREAD

**Issue by gadnis** [DPDBaltics/PrestaShop-1.7#77]
In DPD module settings COD type products zones is `Lithuania`, but customer from Latvia (address country Latvia) can see the carrier as an option.

[screenshot](https://prnt.sc/YxAi3pVxBK0r)

PrestaShop Version 1.7.6.8
PHP Version 7.2.34
MySQL Version 10.6.15-MariaDB-log
DPD Module Version 3.2.18

**Comment by justelis22** [comment]
Hi there @gadnis,

We will check this case and get back to you as soon as we have some updated.

Best Regards,
Invertus Support team.
