### ISSUE TITLE
Third party checkout module support

### ISSUE THREAD

**Issue by zelarg** [DPDBaltics/PrestaShop-1.7#78]
Hi team,

We have a problem using the city selector in third party checkout module (TheCheckout), it seems that for logged-in customers who has city filled in in the address, the 'city' dropdown is disabled.

Even though, all cities are loaded well (see a screenshot), there seems to be some JS script "locking" the field.

![image](https://github.com/DPDBaltics/PrestaShop-1.7/assets/9821742/cd70c2f3-2fc9-4d1e-b332-c7f71df993e9)

Here's a short video of how it behaves, initially, the City field cannot be clicked, only after Street is changed, City field is "unlocked", see here: https://drive.google.com/file/d/1bDtg7Yl9Q3ohRYlrqETgsf9cuNTFkq3v/view?usp=drivesdk

Do you have any suggestion what could be locking / disabling the City field?

Thanks!

**Comment by justelis22** [comment]
Hi there @zelarg,

Could you please send us the zip of the checkout module to our email - support@invertus.eu? 
We will check this case and get back to you as soon as possible.

Best Regards,
Invertus Support team.

**Comment by zelarg** [comment]
@justelis22 Sure, I'm sending the module now, thank you!

**Comment by justelis22** [comment]
@zelarg, thank you! We received the message.

We will do some testing and get back to you once we have some updates.

Thank you for your patience!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hello @zelarg,

We are currently communicating with the DPD team and evaluating the possibility of adding compatibility with the most used (popular) 3rd party checkout modules. The Checkout module is one of them.
This might take a while to get implemented, however it should be done in the future.

I will keep you updated!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @zelarg,

We prepared the [3.2.20 beta release](https://github.com/DPDBaltics/PrestaShop-1.7/releases/tag/v3.2.20-beta), which includes compatibility with the "TheCheckout" module.

You can install the module and test it out to see if everything works good on your shop.

I will be waiting for your feedback!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there,

3.2.20 release was done and it includes the OPC module compatibility.

Best Regards,
Invertus Support team.
