### ISSUE TITLE
Fees not counted

### ISSUE THREAD

**Issue by Stealas** [DPDBaltics/PrestaShop-1.7#80]
Hey,

i have some issue. I am using COD with fees module, but on the label there is no fee counted, everywhere else is fine. Is it possible to fix this? Prestashop 8.1.3 
![Screenshot_61](https://github.com/DPDBaltics/PrestaShop-1.7/assets/158066566/f2c76397-b4d2-4a5f-b6a0-882effd6ed58)

**Comment by justelis22** [comment]
Hi @Stealas,

We will check this issue and get back to you as soon as possible.

Best Regards,
Invertus Support team.

**Comment by Stealas** [comment]
Done.

**Comment by justelis22** [comment]
Hi there @Stealas,
Thanks for waiting.

We have improved to add the total with the fee included to the shipping label.

The changes are already live on the 3.2.20 release - https://github.com/DPDBaltics/PrestaShop-1.7/releases/tag/v3.2.20

Best Regards,
Invertus Support team.
