### ISSUE TITLE
Call to a member function getErrLog() on null

### ISSUE THREAD

**Issue by gadnis** [DPDBaltics/PrestaShop-1.7#84]
Hi,

we get this error in our `prod.log file`: `Call to a member function getErrLog() on null at ..modules/dpdbaltics/dpdbaltics.php:1378)`

it looks like `$parcelPrintResponse` does not exists because it was initialized in try catch block
https://github.com/DPDBaltics/PrestaShop-1.7/blob/21d39218fbb9b73766c6ac6a0d6951f6b23fc43c/dpdbaltics.php#L1357

[and on line 1403](https://github.com/DPDBaltics/PrestaShop-1.7/blob/21d39218fbb9b73766c6ac6a0d6951f6b23fc43c/dpdbaltics.php#L1403)

**Comment by justelis22** [comment]
Hi @gadnis,

Thank you for the information. 
We will check this and get back to you with an update as soon as possible.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi @gadnis,

The fix will be included in the upcoming release 3.2.20.

I will inform you once the beta release is available.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Fixed as per https://github.com/DPDBaltics/PrestaShop-1.7/issues/92
