### ISSUE TITLE
Print label error

### ISSUE THREAD

**Issue by Laimonas-Mituzas** [DPDBaltics/PrestaShop-1.7#87]
PS 8.1.5
module v3.2.19
On trying to print label from BO orders list got EEE-CONECTION_CLOSED
![dpd-label-error](https://github.com/DPDBaltics/PrestaShop-1.7/assets/54275557/4de4af09-6794-4cdd-b9bf-bfe22b322ffa)
Log shows error "Price definition not found."
![dpd-label-error1](https://github.com/DPDBaltics/PrestaShop-1.7/assets/54275557/fcbca6fc-9f04-44c2-a898-616f3c4b70bf)

Is it a problem with module settings?
Price rules are fine
![dpd-label-error2](https://github.com/DPDBaltics/PrestaShop-1.7/assets/54275557/c3f4090d-97b6-4826-bd92-880348e5b975)

**Comment by justelis22** [comment]
Hi there @Laimonas-Mituzas,
Thanks for waiting!

Please clarify if this issue only happens in this shop or if you tried a new PrestaShop installation.
Does the issue happen with each order or only in some specific cases?

Recreated your price rules on the same PrestaShop version, but I could not recreate the issue you attached.

Best Regards,
Invertus Support team.

**Comment by Laimonas-Mituzas** [comment]
I have checked the log and see this error once.
Now I see more new errors, occured few times
![image](https://github.com/DPDBaltics/PrestaShop-1.7/assets/54275557/d453b8c1-9bc0-4819-ac53-1f4d6a2a52b6)
I have checked the address, I see that is really to long
![image](https://github.com/DPDBaltics/PrestaShop-1.7/assets/54275557/61b10695-cf41-4103-a98d-42481d9fe70b)
Error occurs even the DPD pick-up point is selected by client. As you see there is no button for label print.
![image](https://github.com/DPDBaltics/PrestaShop-1.7/assets/54275557/5f8c54f1-4c08-4eca-99bd-04ab46e0e6b4)
![image](https://github.com/DPDBaltics/PrestaShop-1.7/assets/54275557/3c7cb45e-abe9-4668-a0fe-e666827bbfb7)

**Comment by justelis22** [comment]
Hi @Laimonas-Mituzas,

From this screenshot I can see that the whole address is added to the City field:
![image](https://github.com/DPDBaltics/PrestaShop-1.7/assets/103486043/6cd90954-47a9-4ca3-bb1b-d888f5969d6a)

In normal cases this should not happen, so the can be an issue in the checkout for this to happen.

Can you share the shop URL? We would like to take a look at the checkout of this shop. You can send it to support@invertus.eu.

Best Regards,
Invertus Support team.
